### ISSUE TITLE
No such file or directory: 'VERSION'

### ISSUE THREAD

**Issue by hengfengli** [NerdWalletOSS/kinesis-python#7]
Hi there, 

I run the following command `pip3 install kinesis-python`, but I got the following error: 

```bash
Collecting kinesis-python
  Downloading kinesis-python-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b0/m1wbw4x14tn78q7vym9sd8c80000gn/T/pip-build-rinms_kk/kinesis-python/setup.py", line 3, in <module>
        with open('VERSION') as version_fd:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/b0/m1wbw4x14tn78q7vym9sd8c80000gn/T/pip-build-rinms_kk/kinesis-python/
```

I guess the code hasn't been updated to the latest version yet. 

Cheers.

**Comment by borgstrom** [comment]
Latest version has been uploaded to pypi.

**Comment by hengfengli** [comment]
@borgstrom The issue still exists. 

```bash
Collecting kinesis-python
  Using cached kinesis-python-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7z/w4ryds754z56syykzk0mh1000000gn/T/pip-build-qk0es8uu/kinesis-python/setup.py", line 3, in <module>
        with open('VERSION') as version_fd:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7z/w4ryds754z56syykzk0mh1000000gn/T/pip-build-qk0es8uu/kinesis-python/
```

**Comment by borgstrom** [comment]
#10 was just merged.  0.1.5 should be in pypi in a few minutes and should fix this (`VERSION` is now included).
